FROM node:20-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM deps AS builder
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG INTERNAL_ADMIN_API_KEY
ARG TURNSTILE_SECRET_KEY
ARG RATE_LIMIT_WINDOW_MS
ARG RATE_LIMIT_MAX_PUBLIC_REQUESTS
ARG CTA_TRACK_RATE_LIMIT_MAX
ARG DIAGNOSTIC_DUPLICATE_WINDOW_HOURS
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV INTERNAL_ADMIN_API_KEY=$INTERNAL_ADMIN_API_KEY
ENV TURNSTILE_SECRET_KEY=$TURNSTILE_SECRET_KEY
ENV RATE_LIMIT_WINDOW_MS=$RATE_LIMIT_WINDOW_MS
ENV RATE_LIMIT_MAX_PUBLIC_REQUESTS=$RATE_LIMIT_MAX_PUBLIC_REQUESTS
ENV CTA_TRACK_RATE_LIMIT_MAX=$CTA_TRACK_RATE_LIMIT_MAX
ENV DIAGNOSTIC_DUPLICATE_WINDOW_HOURS=$DIAGNOSTIC_DUPLICATE_WINDOW_HOURS
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.ts ./next.config.ts

EXPOSE 3000

CMD ["npm", "run", "start"]
